[build]
  command = "pnpm install && pnpm build"
  publish = "dist/public"

[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/sitemap.xml/"
  to   = "/sitemap.xml"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
